### ISSUE TITLE
UseBug mine des Nains

### ISSUE THREAD

**Issue by cadenza-k** [HollishKid/Gaia#121]
A partir de la baguette d'air (encore elle!), on peux contourner le massacre de gobelins en sautant par la cheminée du volcan pour accéder à la mine.

(Screenshot by bibi)
![2017-08-20_19 22 25](https://user-images.githubusercontent.com/5676901/29497074-e10f19f0-85e1-11e7-9d4d-3bc0130c19ea.png)

**Comment by HollishKid** [comment]
Résolu en ayant posé une double couche de barriers.
Juste assez basse pour ne pas pouvoir en ressortir autrement que par un /spawn ;)

(à moins d'avoir une baguette l'air)
