### ISSUE TITLE
Bloquer le "fly" dans le temple de la terre

### ISSUE THREAD

**Issue by HollishKid** [HollishKid/Gaia#124]
Grâce aux sorts on peut contourner l'énigme du Temple de la Terre.

https://forum.gaia-craft.fr/topic/145/bloquer-le-fly-dans-le-temple-de-la-terre

**Comment by Undertimes** [comment]
On pourrai désactiver les sorts autour et dans le temple complètement? On pourrai alors dire que "&5Une force venant du sol semble bloquer votre magie."

**Comment by Undertimes** [comment]
Ou alors on fais comme pour certains sorts de terre, qui sont bloqués totalement dans la ville d'Athelas.
