### ISSUE TITLE
Interface admin/ console @crashozz

### ISSUE THREAD

**Issue by Axeloow** [HollishKid/Gaia#127]
- Le bouton kick de l'interface admin ne fonctionne pas et agis comme un broadcast

_Sent from my Samsung SM-G361F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by crashoz** [comment]
Oups

**Comment by crashoz** [comment]
C'est réglé, toutes les commandes sur les joueurs sont opérationnelles
