### ISSUE TITLE
Dossier BQ Lauvel génère des erreurs

### ISSUE THREAD

**Issue by crashoz** [HollishKid/Gaia#129]
Il faudrait l'enlever du prod (à l’arrêt) et le mettre dans critical.txt, il a du être rajouté sur le prod par l'auto-updater

**Comment by HollishKid** [comment]
Est-ce qu'on peut ajouter un dossier entier dans critical.txt ?
Je tenterais de faire ceci assez rapidement ; ça ne craint pas d'éteindre le serveur manuellement ce soir tard et de faire l'opération, si @crashoz ?

**Comment by crashoz** [comment]
J'avais oublié cette issue, oui on peut mettre un dossier dans critical.txt (le chemin du dossier sans / à la fin). Et oui il faut l'enlever à la main en stoppant le serveur
