### ISSUE TITLE
Perte d'items de quête

### ISSUE THREAD

**Issue by cadenza-k** [HollishKid/Gaia#132]
PLusieurs joueurs se plaignent récemment de prendre leur fioles pour différentes quêtes, pour ce mois-ci on en a 4 qui ont click dans de l'eau, un autre qui a tenté les 14 fois d'obtenir les fioles, et enfin d'autres dont l'item a simplement disparu:
 
![image](https://user-images.githubusercontent.com/5676901/30772916-47c8ebdc-a066-11e7-8c13-5003f0de55a9.png)

**Comment by HollishKid** [comment]
Je pense que le plus "simple" ici serait de directement ajouter une possibilité de récupérer des fioles de l'air auprès de Aang. Ceci permettrait un débug pour les joueurs actuellement coincés et une solution viable pour l'avenir de récupérer les fioles nécessaires.

**Comment by cadenza-k** [comment]
👍 
Bien qu'il y ai _UN_ doué qui a redemandé 14 fois des fioles à Toph x)
