### ISSUE TITLE
Bug des salaires

### ISSUE THREAD

**Issue by crashoz** [HollishKid/Gaia#27]
Les events d'ajouts de points au salaire ont perdu leur '+'
Je vais vérifier si il n'y en a pas d'autres qui ont disparus.

**Comment by crashoz** [comment]
Après avoir regardé la doc je pense que ça ne change rien.
Est-ce que ces deux lignes sont équivalentes?
* salaire_plus100: point salaire +100
* salaire_plus100: point salaire 100

Pour moi ce n'est pas la même chose. Mais la doc semble dire le contraire.
Qu'en pense @HollishKid ?

**Comment by HollishKid** [comment]
Salut @crashoz 

Ça ne devrait rien changer. C'est uniquement s'il y avait eu un '-' que c'aurait posé problème.
Si dans l'uniformisation tu préfères l'un ou l'autre, BQ ne râlera pas normalement ^^

**Comment by crashoz** [comment]
Alright, on va garder comme c'est sur le master alors, c'est à dire sans les '+'
