### ISSUE TITLE
Ingor-Sancossi

### ISSUE THREAD

**Issue by Cubtomania** [HollishKid/Gaia#33]
Lorsque l'on gagne contre Sancossi, notre journal est mis à jour mais je reçois un message qui s'affiche comme quoi j'ai perdu contre Sancossi --> à retirer, sinon tout est ok.

**Comment by HollishKid** [comment]
@Cubtomania 
Ce bug est survenu pendant les "turbulences" qu'on a eu avec BQ, peux tu confirmer une erreur de code ?

**Comment by Cubtomania** [comment]
Je vérifier @Hollish

**Comment by Cubtomania** [comment]
Vais *

**Comment by HollishKid** [comment]
Note de @GoupilDC16 
Les aides-camps des nains brûlent au soleil.
Modifier le type de mobs ou ajouter un casque dans leur équipement.
