### ISSUE TITLE
Drisgan Package does not exist

### ISSUE THREAD

**Issue by HollishKid** [HollishKid/Gaia#49]
There has been an error: Package in ID 'Drisgan.check_cine' does not exist

**Comment by crashoz** [comment]
C'est dans CommandsRegions ligne ~331, j'ai corrigé sur le FTP
Il faudra intégrer ce fix dans une Pull Request

**Comment by HollishKid** [comment]
Excellente trouvaille :+1: 

On garde le ticket ouvert tant que ce n'est pas intégré dans un PR.
